version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: activejob
    versions:
    - 6.1.2
    - 6.1.3.1
  - dependency-name: actionpack
    versions:
    - 6.1.2
    - 6.1.3.1
  - dependency-name: activerecord
    versions:
    - 6.1.3.1
  - dependency-name: actiontext
    versions:
    - 6.1.2
  - dependency-name: actionmailbox
    versions:
    - 6.1.2
  - dependency-name: activestorage
    versions:
    - 6.1.2
  - dependency-name: actioncable
    versions:
    - 6.1.2
