default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: picturesque_development

test:
  <<: *default
  database: picturesque_test

production:
  <<: *default
  database: picturesque_production
